name: on-push-master

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'clean-archi'
      - 'master'
      

jobs:
  api-test:
    name: api test - run unitest on action
    runs-on: ubuntu-latest
    container: golang:1.17
    services:
      mysql:
        image: mariadb:10.1
        env:
          MYSQL_ROOT_PASSWORD: 22juli1998
        ports:
          - 3306:3306
    strategy:
      matrix:
        go: [ '1.17' ]
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v2
      - name: create database
        run: |
          apt-get update
          apt-get install -y mariadb-client
          mysql --host mysql -uroot -p22juli1998 -e "CREATE DATABASE IF NOT EXIST wastebank_miniproject"
      - name: running unitest
        run: |
          mv ./app/config/example-config.json ./app/config/config.json
          go mod tidy
          go test ./... -cover -failfast